// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi78dbifGVjVqct2XNXjAHGl-76TSTIyo',
    appId: '1:924863060588:web:01150130097735f80f5649',
    messagingSenderId: '924863060588',
    projectId: 'y-chat-6873d',
    authDomain: 'y-chat-6873d.firebaseapp.com',
    storageBucket: 'y-chat-6873d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJgbtAnBHid1QO8uZa3Nnto0ImYpdZEbs',
    appId: '1:924863060588:android:f3324b9acd72d08d0f5649',
    messagingSenderId: '924863060588',
    projectId: 'y-chat-6873d',
    storageBucket: 'y-chat-6873d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWSiPzaueoy9o6WSiJn2dRyTldh8IRjs',
    appId: '1:924863060588:ios:3b7047f22e4358680f5649',
    messagingSenderId: '924863060588',
    projectId: 'y-chat-6873d',
    storageBucket: 'y-chat-6873d.appspot.com',
    iosClientId: '924863060588-o08515uhn3vs4oo427c3ie852qllihhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqWSiPzaueoy9o6WSiJn2dRyTldh8IRjs',
    appId: '1:924863060588:ios:2fc75758f0f0aa640f5649',
    messagingSenderId: '924863060588',
    projectId: 'y-chat-6873d',
    storageBucket: 'y-chat-6873d.appspot.com',
    iosClientId: '924863060588-90f34ds1g3a5vj2el2bec2nqso1lasjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp.RunnerTests',
  );
}
